name: componets_kombat
description: A new Flutter package project.
version: 0.0.14
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_mobx: ^2.0.6+5
  font_awesome_flutter: ^10.5.0 
  flutter_spinkit: ^5.2.0
  provider: ^6.0.5
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  rflutter_alert: ^2.0.7
  dropdown_button2: ^1.0.7
  flutter_phoenix: ^1.1.1
  # flutter_file_downloader: ^1.1.2
  # flutter_local_notifications: ^15.1.0+1
  ## terminar de implementar

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  connectivity_plus: ^4.0.1
  http: ^0.13.6
  
  mask_text_input_formatter: ^2.0.0
  flutter_barcode_scanner: ^2.0.0
 
  form_field_validator: ^1.1.0
   
  qr_flutter: ^4.0.0

  crypto: ^3.0.2
  dart_jsonwebtoken: ^2.4.2
  path_provider: ^2.0.11
  firebase_core_platform_interface: ^4.5.1
  dartz: ^0.10.1
  string_similarity: ^2.0.0
  mockito: ^5.3.2
  flutter_masked_text2: ^0.9.1
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  geocoder_plus: ^0.0.1
  internet_connection_checker: ^1.0.0+1  
  google_fonts: ^4.0.4
  animated_text_kit: ^4.2.2
  intl: ^0.18.0
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3 

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
     - assets/
     - assets/itajuba_contorno.png

     - assets/login/
     - assets/alerts/
     - assets/icons/
     - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
